In [42]:
import pandas as pd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Match genera names to a higher level in plant taxonomy

This is because for the work I'm doing for a viz I need to coarse data - I've got too many genera

In [59]:
df_taxons = pd.read_csv('backbone-current/Taxon.tsv', sep='\t')    # from the taxonomy sheet

/Users/martina/Desktop/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3169: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [60]:
df_genera = pd.read_csv('genera_list.csv')

In [66]:
df_taxons.size
len(df_taxons)

41752912

1815344

In [62]:
set(df_taxons['kingdom'])

{'Animalia',
 'Archaea',
 'Bacteria',
 'Chromista',
 'Fungi',
 'Plantae',
 'Protozoa',
 'Viruses',
 'incertae sedis'}

In [63]:
# take only plants - I think there won't be shared names between kindgoms but good to reduce upfront
df_taxons = df_taxons[df_taxons.kingdom=='Plantae']

In [65]:
df_taxons = df_taxons.dropna(subset=['genus'])   # drop all those with no genus (there are) as I'll search by it

In [67]:
df_taxons.head(2)
df_taxons.columns

,taxonID,datasetID,parentNameUsageID,acceptedNameUsageID,originalNameUsageID,scientificName,scientificNameAuthorship,canonicalName,genericName,specificEpithet,...,namePublishedIn,taxonomicStatus,nomenclaturalStatus,taxonRemarks,kingdom,phylum,class,order,family,genus
16694,1010279,7ddf754f-d193-4cc9-b351-99906754a03b,9001.0,NaN,NaN,"Hyalosiphonia Okamura, 1909","Okamura, 1909",Hyalosiphonia,Hyalosiphonia,NaN,...,NaN,accepted,NaN,NaN,Plantae,Rhodophyta,Florideophyceae,Gigartinales,Dumontiaceae,Hyalosiphonia
16894,1010566,aacd816d-662c-49d2-ad1a-97e66e2a2908,2660953.0,2661140.0,NaN,Fucus gelatinosus Desf.,Desf.,Fucus gelatinosus,Fucus,gelatinosus,...,NaN,synonym,NaN,NaN,Plantae,Rhodophyta,Florideophyceae,Ceramiales,Rhodomelaceae,Laurencia

Index(['taxonID', 'datasetID', 'parentNameUsageID', 'acceptedNameUsageID',
       'originalNameUsageID', 'scientificName', 'scientificNameAuthorship',
       'canonicalName', 'genericName', 'specificEpithet',
       'infraspecificEpithet', 'taxonRank', 'nameAccordingTo',
       'namePublishedIn', 'taxonomicStatus', 'nomenclaturalStatus',
       'taxonRemarks', 'kingdom', 'phylum', 'class', 'order', 'family',
       'genus'],
      dtype='object')

In [88]:
df_taxons.groupby('taxonomicStatus').count()

,taxonID,datasetID,parentNameUsageID,acceptedNameUsageID,originalNameUsageID,scientificName,scientificNameAuthorship,canonicalName,genericName,specificEpithet,...,nameAccordingTo,namePublishedIn,nomenclaturalStatus,taxonRemarks,kingdom,phylum,class,order,family,genus
taxonomicStatus,,,,,,,,,,,,,,,,,,,,,
accepted,577618,577618,577618,1,97093,577618,542004,573814,573814,553669,...,0,520555,0,3336,577618,576901,576295,575574,575110,577618
doubtful,85214,85214,85214,0,1215,85214,82852,84895,84895,61709,...,0,58763,0,27155,85214,81570,80456,79000,79173,85214
heterotypic synonym,50231,50172,50231,50231,8202,50231,49956,50231,50231,50205,...,0,48907,0,1242,50231,50231,50231,50229,50229,50231
homotypic synonym,292501,290949,292501,292501,104713,292501,292348,292501,292501,292375,...,0,173351,0,20315,292501,292496,292496,292490,292488,292501
misapplied,640,639,640,640,109,640,579,638,638,638,...,0,279,0,39,640,640,640,640,640,640
proparte synonym,1145,1132,1145,1145,190,1145,747,1135,1135,1036,...,0,368,0,35,1145,1145,1145,1145,1145,1145
synonym,807995,806082,807995,807994,183707,807995,777481,805555,805555,780059,...,0,558048,0,17355,807995,807912,807842,807683,807788,807995

In [68]:
# lower case to all cols of interest - easier to deal with, not worrying on case
df_taxons['genus']  = df_taxons['genus'].str.lower()
df_taxons['family']  = df_taxons['family'].str.lower()
df_taxons['order']  = df_taxons['order'].str.lower()
df_taxons['class']  = df_taxons['class'].str.lower()
df_taxons['phylum']  = df_taxons['phylum'].str.lower()

In [69]:
df_taxons[df_taxons.scientificName.str.contains('Capsicum annuum')].head()

,taxonID,datasetID,parentNameUsageID,acceptedNameUsageID,originalNameUsageID,scientificName,scientificNameAuthorship,canonicalName,genericName,specificEpithet,...,namePublishedIn,taxonomicStatus,nomenclaturalStatus,taxonRemarks,kingdom,phylum,class,order,family,genus
1345616,2932944,7ddf754f-d193-4cc9-b351-99906754a03b,2932937.0,NaN,NaN,Capsicum annuum L.,L.,Capsicum annuum,Capsicum,annuum,...,L. In: Sp. Pl. 188. (1753).,accepted,NaN,NaN,Plantae,tracheophyta,magnoliopsida,solanales,solanaceae,capsicum
1861652,3799172,d9a4eedb-e985-4456-ad46-3df8472e00e8,2932937.0,2932943.0,NaN,Capsicum annuum var. violaceum Voss,Voss,Capsicum annuum violaceum,Capsicum,annuum,...,NaN,synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,solanales,solanaceae,capsicum
1861662,3799185,7ddf754f-d193-4cc9-b351-99906754a03b,2932944.0,3799221.0,3798744.0,Capsicum annuum var. minus (Fingerh.) Shinners,Shinners (Fingerh.),Capsicum annuum minus,Capsicum,annuum,...,Shinners. In: Baileya 4: 82. (1956).,synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,solanales,solanaceae,capsicum
1861664,3799187,d9a4eedb-e985-4456-ad46-3df8472e00e8,2932937.0,2932938.0,7299413.0,Capsicum annuum var. microcarpum (Cav.) Voss,Voss (Cav.),Capsicum annuum microcarpum,Capsicum,annuum,...,NaN,synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,solanales,solanaceae,capsicum
1861671,3799194,f382f0ce-323a-4091-bb9f-add557f3a9a2,2932937.0,2932944.0,NaN,Capsicum annuum f. luteum Kuntze,Kuntze,Capsicum annuum luteum,Capsicum,annuum,...,NaN,synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,solanales,solanaceae,capsicum

In [71]:
len(df_taxons[df_taxons.genus=='abelmoschus'].groupby('family').count())

1

In [73]:
df_taxons[df_taxons.family=='malvaceae'].groupby('genus').count()

,taxonID,datasetID,parentNameUsageID,acceptedNameUsageID,originalNameUsageID,scientificName,scientificNameAuthorship,canonicalName,genericName,specificEpithet,...,nameAccordingTo,namePublishedIn,taxonomicStatus,nomenclaturalStatus,taxonRemarks,kingdom,phylum,class,order,family
genus,,,,,,,,,,,,,,,,,,,,,
abelmoschus,218,218,218,188,48,218,214,218,218,215,...,0,160,218,0,8,218,218,218,218,218
abroma,26,26,26,20,0,26,26,26,26,23,...,0,22,26,0,1,26,26,26,26,26
abutilodes,1,1,1,0,0,1,1,1,1,0,...,0,1,1,0,0,1,1,1,1,1
abutilon,756,756,756,476,133,756,733,756,756,748,...,0,601,756,0,23,756,756,756,756,756
acaulimalva,77,77,77,54,24,77,77,77,77,76,...,0,65,77,0,0,77,77,77,77,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wheeleroxylon,2,2,2,0,0,2,2,2,2,1,...,0,0,2,0,0,2,2,2,2,2
wissadula,195,195,195,137,59,195,190,195,195,194,...,0,149,195,0,13,195,195,195,195,195
woodianthus,2,2,2,0,0,2,2,2,2,1,...,0,2,2,0,0,2,2,2,2,2
xylon,1,1,1,0,0,1,1,1,1,0,...,0,1,1,0,0,1,1,1,1,1
xylum,1,1,1,0,0,1,1,1,1,0,...,0,0,1,0,0,1,1,1,1,1

In [76]:
df_genera.head(2)

         Genus
0  abelmoschus
1        abrus

In [75]:
# lower case on the genera sheer as well

df_genera['Genus'] = df_genera['Genus'].str.lower()

In [77]:
# get info on all the genera I have, build a new sheet with all taxonomy info

genera = list(df_genera['Genus'])
len(genera)

1113

In [138]:
# genus acrocarpus has 2 families! See how big in number of lines
df_taxons[df_taxons.genus=='alkanna'].groupby('family').count() \
     .sort_values('genus', ascending=False).reset_index().iloc[0]['family']

#df_taxons[(df_taxons.genus=='acrocarpus') & (df_taxons.family=='gelidiaceae')]


df_taxons[df_taxons.genus=='alkanna'].groupby(['family', 'order', 'class', 'phylum']).count() \
     .sort_values('genus', ascending=False).reset_index()[['family', 'order', 'class', 'phylum', 'genus']]

'boraginaceae'

         family        order          class        phylum  genus
0  boraginaceae  boraginales  magnoliopsida  tracheophyta    199
1    lythraceae     myrtales  magnoliopsida  tracheophyta      1

In [133]:
# # THIS IS just to check
# # there are some genera which map to more than one family, or more than one order, or class etc
# # it'll likely be mistakes - we take the family/order/class/... where most of items for that genus map to (majority)
# (in next cell)

print('genus - family')
for genus in genera:
    if len(df_taxons[df_taxons.genus==genus].groupby('family').count()) > 1:
        print(genus)

genus - family
acrocarpus
ageratum
albizia
alkanna
allium

KeyboardInterrupt:

In [119]:
# we're using the most populated of the higher levels for that genus as per above

phylum, class_, order, family, genus = [], [], [], [], []
i = 0
for g in genera[:]:    # search in taxon sheet
    
    # check if there first - otehrwise do not cosider at all
    if len(df_taxons[df_taxons.genus==g]) > 0:
        
        genus.append(g)
        
        max_ = df_taxons[df_taxons.genus==g].groupby(['family', 'order', 'class', 'phylum']) \
                 .count() \
                 .sort_values('genus', ascending=False).reset_index().iloc[0]
        
        family.append(max_['family'])
        order.append(max_['order'])
        class_.append(max_['class'])
        phylum.append(max_['phylum'])
    
    i += 1
    
    if i % 50 == 0:
        print(i)

50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100

In [120]:
df = pd.DataFrame({
    'genus': genus,
    'family': family,
    'order': order,
    'class': class_,
    'phylum': phylum
})

In [121]:
len(df_genera), len(df)   # this to see how many we lose (those in the Svalbard sheet and not in the taxonomy one)

(1113, 1044)

In [139]:
# a few sanity checks (can check on wikipedia too to be sure)

df[df.genus=='alkanna']

      genus        family        order          class        phylum
36  alkanna  boraginaceae  boraginales  magnoliopsida  tracheophyta

In [140]:
df_taxons[df_taxons.genus=='alkanna']

,taxonID,datasetID,parentNameUsageID,acceptedNameUsageID,originalNameUsageID,scientificName,scientificNameAuthorship,canonicalName,genericName,specificEpithet,...,namePublishedIn,taxonomicStatus,nomenclaturalStatus,taxonRemarks,kingdom,phylum,class,order,family,genus
1339719,2926056,7ddf754f-d193-4cc9-b351-99906754a03b,2498.0,NaN,NaN,Alkanna Tausch,Tausch,Alkanna,Alkanna,NaN,...,"Tausch. In: Flora, 7: 234. (1824).",accepted,NaN,NaN,Plantae,tracheophyta,magnoliopsida,boraginales,boraginaceae,alkanna
1521941,3230730,f382f0ce-323a-4091-bb9f-add557f3a9a2,2498.0,2926056.0,NaN,Camptocarpus K.Koch,K.Koch,Camptocarpus,Camptocarpus,NaN,...,NaN,synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,boraginales,boraginaceae,alkanna
1522590,3231591,046bbc50-cae2-47ff-aa43-729fbf53f7c5,6684.0,NaN,NaN,"Alkanna Adans., 1763","Adans., 1763",Alkanna,Alkanna,NaN,...,"Fam. Pl. (Adanson) 2: 444, 514. 1763",doubtful,NaN,NaN,Plantae,tracheophyta,magnoliopsida,myrtales,lythraceae,alkanna
2012258,4059392,7ddf754f-d193-4cc9-b351-99906754a03b,5341257.0,7294993.0,7971805.0,Onochilis tinctoria (L.) Bubani,Bubani (L.),Onochilis tinctoria,Onochilis,tinctoria,...,"Bubani. In: Fl. Pyren, 1: 491. (1897).",homotypic synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,boraginales,boraginaceae,alkanna
2012713,4060028,7ddf754f-d193-4cc9-b351-99906754a03b,5341257.0,7294993.0,7971805.0,Rhytispermum tinctorium (L.) Link,Link (L.),Rhytispermum tinctorium,Rhytispermum,tinctorium,...,Link. In: Handb. 1: 579. (1829).,synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,boraginales,boraginaceae,alkanna
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6507154,10911093,7ddf754f-d193-4cc9-b351-99906754a03b,5341257.0,7294993.0,NaN,Nonea violacea Aucher ex A.DC.,Aucher ex A.DC.,Nonea violacea,Nonea,violacea,...,Aucher ex A. DC. In: DC. Prod. 10: 100. (1846).,heterotypic synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,boraginales,boraginaceae,alkanna
6577248,10981188,7ddf754f-d193-4cc9-b351-99906754a03b,2926056.0,5661238.0,NaN,Alkanna orientalis subsp. hellenica Boiss.,Boiss.,Alkanna orientalis hellenica,Alkanna,orientalis,...,NaN,synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,boraginales,boraginaceae,alkanna
6596365,11000305,e85115a0-ecc8-4c1f-9908-821d5a18f80b,2926056.0,NaN,NaN,"Alkanna orientalis Linnaeus, 1753","Linnaeus, 1753",Alkanna orientalis,Alkanna,orientalis,...,NaN,doubtful,NaN,Possible variant of Alkanna orientalis (L.) Bo...,Plantae,tracheophyta,magnoliopsida,boraginales,boraginaceae,alkanna
6647044,11050985,7ddf754f-d193-4cc9-b351-99906754a03b,2926056.0,5661254.0,NaN,Alkanna frigida subsp. pallida Bornm.,Bornm.,Alkanna frigida pallida,Alkanna,frigida,...,NaN,synonym,NaN,NaN,Plantae,tracheophyta,magnoliopsida,boraginales,boraginaceae,alkanna
6688569,11092510,046bbc50-cae2-47ff-aa43-729fbf53f7c5,2926056.0,NaN,NaN,"Alkanna sumbulii Yıld., 2013","Yıld., 2013",Alkanna sumbulii,Alkanna,sumbulii,...,Ot Sist. Bot. Dergisi 20(2): 3. 2013 [31 Dec 2...,doubtful,NaN,Possible variant of Alkanna sumbulii Yild.,Plantae,tracheophyta,magnoliopsida,boraginales,boraginaceae,alkanna

In [141]:
# spit to CSV so I can paste back in google sheet

df.to_csv('genus_taxonomy.csv', index=False)